### ISSUE TITLE
mac bindings with links to static dependencies test not working 

### ISSUE THREAD

**Issue by jhagans3** [Storj/node-libstorj#38]
```
npm test

> storj@5.0.0-beta test .../node-libstorj
> mocha test/**.test.js --recursive

.../node-libstorj/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: dlopen(.../node-libstorj/build/Release/storj.node, 1): Symbol not found: _nettle_aes256_encrypt
  Referenced from: .../node-libstorj/build/Release/storj.node
  Expected in: flat namespace
 in .../node-libstorj/build/Release/storj.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (.../node-libstorj/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (.../node-libstorj/index.js:3:37)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../node-libstorj/test/index.test.js:6:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at .../node-libstorj/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (.../node-libstorj/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (.../node-libstorj/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (.../node-libstorj/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
npm ERR! Test failed.  See above for more details.
```

**Comment by braydonf** [comment]
Looks like `libnettle` isn't getting linked. May need to add `OTHER_LDFLAGS` to `xcode_settings`:

```
'link_settings': {
  'xcode_settings': {
    'OTHER_LDFLAGS': [
      ''<!(node ./binding.js ldflags)'',
    ]
  }
}
```

**Comment by jhagans3** [comment]
updated binding.gyp to (ignore formatting)
```
'link_settings': {
     'xcode_settings': {
       'OTHER_LDFLAGS': [ ''<!(node ./binding.js ldflags)'' ],
      },
      'ldflags': [
        '<!(node ./binding.js ldflags)'
      ]
    }
```
result 60 test pass

**Comment by braydonf** [comment]
Nice!
